Story2 add item
Albertoroldanq/collectors-app pull request #7
Opened 2021-08-04 09:59 UTC by Albertoroldanq

I think the website meets the requirements, but I am not sure if the code correctly done

2021-08-04 15:05 UTC, norayna commented on index.php
> +if(count($_SESSION) && isset($_POST)) {
the check `count($_SESSION)` is not really working - i still get this error when opening the page for the first time:
![image](https://user-images.githubusercontent.com/25844355/128205252-b207755c-f959-4ff9-85ea-5d20f74df875.png)

hint: check that the session has the right number of things in it

2021-08-04 15:07 UTC, norayna requested changes
only small changes requested

2021-08-04 15:19 UTC, Albertoroldanq commented on index.php
> +if(count($_SESSION) && isset($_POST)) {
Thanks! Let's see if it works now...

2021-08-04 15:19 UTC, Albertoroldanq commented on style.css
>  h1{
I will update it in a new task :)

2021-08-05 09:39 UTC, norayna approved these changes

2021-08-05 09:39 UTC, merged